### ISSUE TITLE
bulid this project error 

### ISSUE THREAD

**Issue by xlj44400** [ps5-payload-dev/offact#1]
linux make error 

[root@VM-8-15-centos offact-master]# ls
assets  LICENSE  main.c  Makefile  offact.c  offact.h  README.md  SDL_listui.c  SDL_listui.h
[root@VM-8-15-centos offact-master]# make 
xxd -i assets/font.ttf font.h
xxd -i assets/nav.wav snd_nav.h
/root/ps5_test/ps5-payload-sdk/bin/prospero-clang -o OffAct.elf main.c SDL_listui.c offact.c -O2 -Wall -Wno-format-truncation `/root/ps5_test/ps5-payload-sdk/target/bin/sdl2-config --cflags --libs` -lSDL2_ttf `/root/ps5_test/ps5-payload-sdk/target/bin/freetype-config --libs` -lSDL2_mixer -lSceRegMgr
/bin/sh: /root/ps5_test/ps5-payload-sdk/target/bin/sdl2-config: 没有那个文件或目录
/bin/sh: /root/ps5_test/ps5-payload-sdk/target/bin/freetype-config: 没有那个文件或目录
/root/ps5_test/ps5-payload-sdk/bin/clang:行32: /clang: 没有那个文件或目录
make: *** [OffAct.elf] 错误 127

what is PS5_SYSROOT ?

**Comment by john-tornblom** [comment]
Please post log messages that are all in English.

PS5_SYSROOT is an envvar pointing to libraries, you don't seem to have SDL2 etc in there.

See: https://github.com/ps5-payload-dev/pacbrew-repo/blob/main/ci.sh for script on how to install that
