### ISSUE TITLE
The elf was sent successfully but the account was not activated successfully. PS5 did not respond

### ISSUE THREAD

**Issue by xlj44400** [ps5-payload-dev/offact#2]
The elf was sent successfully but the account was not activated successfully. PS5 did not respond

Can you give me a detailed introduction on what needs to be done to activate the account after sending the elf? Or can you add some documentation?

**Comment by xlj44400** [comment]
![image](https://github.com/user-attachments/assets/c02326c7-5048-43b4-a818-0c09cf07679b)

**Comment by john-tornblom** [comment]
Why are you sending me a screenshot of text? Just send the text and stop wasting my time, yeez.
If you do not intend to contribute with PRs, wait for a tagged release.

**Comment by xlj44400** [comment]
thank you for your contribution

I have solved it
